export const GET_INFO = '@@boards/GET_INFORMATION'
export const CREATE_THREAD = '@@boards/CREATE_THREAD'
export const CREATE_POST = '@@boards/CREATE_POST'
export const HIDE_NAVIGATION = '@@boards/HIDE_OR_SHOW_NAVIGATION'
export const SHOW_MODAL = '@@/SHOW_OR_HIDE_MODAL'
